### ISSUE TITLE
Validate form

### ISSUE THREAD

**Issue by JaimeGonz** [BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2#3]
### Tasks
- [x] Show error texts on empty fields
- [x] Validate email format
- [x] Validate password format
- [x] Select checkboxes
- [x] Validate required fields
