### ISSUE TITLE
My Flight view component

### ISSUE THREAD

**Issue by Raibrr** [BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2#6]
### Tasks
- [ ] Add Title component to view.
- [ ] Add Card component.
- [ ] Add List to Cards.
- [ ] Add float button.
